### ISSUE TITLE
Socket.io > Session Chart: The Chargers and Charts are not refreshed when a session is on going on production landscape

### ISSUE THREAD

**Issue by serge-fabiano** [sap-labs-france/ev-dashboard#1240] opened 2020-03-08 13:38 UTC

**Comment by LucasBrazi06** [comment] 2020-05-14 08:13
We have the issue reported by Frank @SAP reception desk, also not working in the giant iPad.
You could have a look at it this afternoon.

**Comment by LucasBrazi06** [comment] 2020-05-14 08:13
god-prio ;-)

**Comment by jerome-benoit** [comment] 2020-05-14 17:55
The bug reproducibility is still not evident given all the usage patterns listed in that issue, so goes its resolution. 
On the Giant iPad, it seems 100% reproducible. So appointment will be taken with the IT in order to work on it with a mouse and a keyboard.

**Comment by LucasBrazi06** [comment] 2020-05-16 00:00
Pop-up still closes when background refresh occurs.

**Comment by LucasBrazi06** [comment] 2020-05-16 00:35
I removed a listener that closed all the pop-ups after a charging station refresh.
Let's see.

**Comment by jerome-benoit** [comment] 2020-05-19 18:00
I think I've narrowed down that issue with the debug logs: 

The socket.io initialisation is only done after a login phase because of the need to authorise it with the Jwt token. But when you already have a Jwt token on your browser, the login function is not called again and the socket.io initialisation is not done. I will to hook it in the dashboard init if there's already a Jwt token.

**Comment by LucasBrazi06** [comment] 2020-05-19 18:58
> I think I've narrowed down that issue with the debug logs:
> 
> The socket.io initialisation is only done after a login phase because of the need to authorise it with the Jwt token. But when you already have a Jwt token on your browser, the login function is not called again and the socket.io initialisation is not done. I will to hook it in the dashboard init if there's already a Jwt token.

Excellent !
Let's see if it'll work out after this fix.

**Comment by jerome-benoit** [comment] 2020-05-26 19:58
> > The socket.io initialisation is only done after a login phase because of the need to authorise it with the Jwt token. But when you already have a Jwt token on your browser, the login function is not called again and the socket.io initialisation is not done. I will try to hook it in the dashboard init if there's already a Jwt token.
> 
> Excellent !
> Let's see if it'll work out after this fix.

So far so good: one socket.io connection per browser tab to refresh each tab, socket.io reconnect successfully on a per browser tab basis whatever is the number of browsers and tabs opened. 

I still think that at some point to avoid to overload the rest services because of socket.io, the socket.io server will need to be split out but that not before an important usage of the dashboard.

**Comment by LucasBrazi06** [comment] 2020-05-27 09:31
> So far so good: always one socket.io connection per browser tab to refresh each tab, socket.io reconnect successfully on a per browser tab basis whatever is the number of browsers and tabs opened.
> 
> I still think that at some point to avoid to overload the rest services because of socket.io, the socket.io server will need to be split out but that not before an important usage of the dashboard.

Ok thank you.
Yes we'll split it when we'll have million users :-)

**Comment by jerome-benoit** [comment] 2020-06-01 11:00
The issue is back on production SCP landscape only. It works everywhere else.

**Comment by jerome-benoit** [comment] 2020-06-03 09:28
And now, it works correctly again on the production landscape. 

Next time, maybe try to restart the REST application to see if it fix it or not.

**Comment by LucasBrazi06** [comment] 2020-06-03 09:40
> And now, it works correctly again on the production landscape.
> 
> Next time, maybe try to restart the REST application to see if it fix it or not.

Weird anyway !

**Comment by fcoutellier** [comment] 2020-07-21 12:00
I close this issue and will reopen a new one later one if necessary

**Closed as completed by fcoutellier** 2020-07-21 12:00 UTC
Labels: bug, god-prio
